### ISSUE TITLE
ImportError: cannot import name '__version__'

### ISSUE THREAD

**Issue by GentilStar** [Traumatism/Squiz#3]
root@gentiluwu:~/Squiz-main/squiz# python3 -m squiz GentilStar
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/Squiz-main/squiz/squiz.py", line 10, in <module>
    from squiz import __version__
  File "/root/Squiz-main/squiz/squiz.py", line 10, in <module>
    from squiz import __version__
ImportError: cannot import name '__version__'

**Comment by InternetMoha** [comment]
Did you manage to get it running?
