### ISSUE TITLE
rich-click module not found, but installed with pip and already satisfied

### ISSUE THREAD

**Issue by oasn** [Traumatism/Squiz#7]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Shadow\Desktop\Squiz-main\squiz\__main__.py", line 1, in <module>
    from squiz.squiz import run
  File "C:\Users\Shadow\Desktop\Squiz-main\squiz\squiz.py", line 3, in <module>   
    import rich_click as click  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'rich_click'

**Comment by lhitori** [comment]
Try to use use `pip` through `python -m pip`.

**Comment by lhitori** [comment]
I updated the requirements.txt (`python -m pip install -r requirements.txt`). I'm now using a virtual env which should prevent error like this in the future !
